import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppinsFont = localFont({
  src: [
    {
      path: "./fonts/Poppins-Regular.woff",
      weight: "400",
    },
    {
      path: "./fonts/Poppins-Medium.woff",
      weight: "500",
    },
    {
      path: "./fonts/Poppins-SemiBold.woff",
      weight: "600",
    },
    {
      path: "./fonts/Poppins-Bold.woff",
      weight: "700",
    },
  ],
  variable: "--font-poppins",
});

const rubikFont = localFont({
  src: [
    {
      path: "./fonts/Rubik-variable.ttf",
      weight: "100 900",
    },
  ],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} ${rubikFont.variable} antialiased flex flex-col gap-[121px] items-center`}
      >
        {children}
      </body>
    </html>
  );
}
